-- ============================================================================
-- Seed data, generated from the frontend's src/helper/*.ts files.
-- Usage: psql "$DATABASE_URL" -f sql/seed.sql
-- (safe to re-run: it clears the tables first)
-- ============================================================================
ALTER TABLE "portfolios" ALTER COLUMN "updatedAt" SET DEFAULT now();

TRUNCATE TABLE "intro", "portfolios", "carousel_items", "services", "education", "work_experience", "skills", "testimonials", "contact_info", "contact_messages" RESTART IDENTITY CASCADE;


-- Portfolio projects + gallery images
INSERT INTO "portfolios" ("slug", "featured", "title", "companyBuiltWith", "desc", "projectColor", "projectText", "outcome", "link", "moreInfoLink", "projectLogo", "image", "status", "skills", "order") VALUES ('cardo', true, 'Cardo', 'Carthagos', 'Cardo is a knowledge-sharing platform designed to bridge mentorship gaps in the labor market by connecting professionals with consultants from top American firms. Built as part of the Carthagos team, I led the frontend development of the platform using React, JavaScript. I implemented key features such as landing pages, dashboards, LinkedIn-based authentication, user onboarding, scheduling via Calendly, Jotform integrations, and a real-time chat system using Socket.IO. I worked closely with the backend team to integrate REST APIs, ensuring a seamless and responsive user experience.', '#5555DB', '#ffffff', 'The platform successfully launched and connected professionals to expert mentors in real-time. It was praised for its intuitive UI, fast performance, and real-time chat experience. My frontend contributions enabled efficient scheduling and interaction between users and mentors, contributing to the platform''s adoption and growth.', 'http://www.hellocardo.org/', 'https://www.carthagos.com/projects/Cardo', 'portfolio/cardo/logo.svg', 'portfolio/cardo/cover.png', 'live', ARRAY['HTML/CSS', 'JavaScript', 'React.js', 'Redux', 'Web Sockets', 'Calendly', 'Express.js', 'Node.js', 'MongoDB', 'Git']::TEXT[], 0);
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/cardo/cardo1.png', 'Main', 'Cardo', 'main', 0, (SELECT "id" FROM "portfolios" WHERE "slug" = 'cardo'));
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/cardo/cardo2.png', 'Why Cardo', 'Cardo', 'secondary', 1, (SELECT "id" FROM "portfolios" WHERE "slug" = 'cardo'));
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/cardo/cardo3.png', 'How It Works', 'Cardo', 'alternative', 2, (SELECT "id" FROM "portfolios" WHERE "slug" = 'cardo'));
INSERT INTO "portfolios" ("slug", "featured", "title", "companyBuiltWith", "desc", "projectColor", "projectText", "outcome", "link", "moreInfoLink", "projectLogo", "image", "status", "skills", "order") VALUES ('luminous', true, 'Luminous', 'Carthagos', 'Luminous is a vacation rental platform that enables property owners to rent out spaces to travelers—offering shared spaces, private rooms, or entire homes. I worked on both the backend and frontend, initially building the system using EJS templates and later migrating it entirely to React.js as per the client’s request.
I implemented a secure JWT-based authentication system, booking logic, scheduling, payment integration using Stripe, and dashboards for both users and property owners. On the frontend, I translated Figma designs into responsive HTML, built multi-step forms, private routes, and dynamic calendar-based booking interfaces.', '#FF5607', '#ffffff', 'The platform launched successfully and streamlined the process for both travelers and hosts. It featured intuitive navigation, a secure booking flow, and flexible scheduling options. My work helped reduce booking errors, enhance the user experience, and increase user engagement.', 'https://www.itsluminous.ca/', NULL, 'portfolio/luminous/logo.svg', 'portfolio/luminous/cover.png', 'live', ARRAY['HTML/CSS', 'JavaScript', 'React.js', 'Redux', 'Express.js', 'Node.js', 'Stripe', 'Sequalize', 'MySQL', 'Stripe']::TEXT[], 1);
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/luminous/luminous1.png', 'Main', 'Luminous', 'main', 0, (SELECT "id" FROM "portfolios" WHERE "slug" = 'luminous'));
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/luminous/luminous2.png', 'Why Luminous', 'Luminous', 'secondary', 1, (SELECT "id" FROM "portfolios" WHERE "slug" = 'luminous'));
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/luminous/luminous3.png', 'How It Works', 'Luminous', 'alternative', 2, (SELECT "id" FROM "portfolios" WHERE "slug" = 'luminous'));
INSERT INTO "portfolios" ("slug", "featured", "title", "companyBuiltWith", "desc", "projectColor", "projectText", "outcome", "link", "moreInfoLink", "projectLogo", "image", "status", "skills", "order") VALUES ('gathr', true, 'Gathr', 'Carthagos', 'Gathr is a product feedback platform that connects companies with consumers by shipping curated gift boxes to subscribers, who in return provide first-hand reviews of the products. As part of the Carthagos team, I was responsible for developing the frontend landing pages of the website, ensuring they were responsive, visually engaging, and optimized for conversions.
I worked extensively with WordPress and Elementor to build dynamic, customizable sections, while integrating Swiper.js for interactive sliders. I also optimized performance, SEO, and mobile responsiveness to improve the user experience and ensure better reach for the platform.', '#ED4C4C', '#FFFFFF', 'The project launched successfully, providing Gathr with an attractive and user-friendly website to onboard new subscribers and showcase its unique value. My contributions improved engagement on landing pages and supported the growth of the platform by making the product feedback process more accessible and appealing to end-users.', 'https://hellogathr.com/', 'https://www.carthagos.com/projects/Gathr', 'portfolio/gathr/logo.svg', 'portfolio/gathr/cover.png', 'live', ARRAY['HTML/CSS', 'JavaScript', 'jQuery', 'WordPress', 'Elementor', 'Swiper.js', 'Responsive Design', 'SEO Optimization']::TEXT[], 2);
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/gathr/gathr1.png', 'Main', 'Luminous', 'main', 0, (SELECT "id" FROM "portfolios" WHERE "slug" = 'gathr'));
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/gathr/gathr2.png', 'Why gathr', 'gathr', 'secondary', 1, (SELECT "id" FROM "portfolios" WHERE "slug" = 'gathr'));
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/gathr/gathr3.png', 'How It Works', 'gathr', 'alternative', 2, (SELECT "id" FROM "portfolios" WHERE "slug" = 'gathr'));
INSERT INTO "portfolios" ("slug", "featured", "title", "companyBuiltWith", "desc", "projectColor", "projectText", "outcome", "link", "moreInfoLink", "projectLogo", "image", "status", "skills", "order") VALUES ('mimoo', false, 'Mimoo', 'Carthagos', 'Mimoo is a Portuguese engagement marketing platform that helps brands gain valuable audience insights by offering products as rewards for completing gamified missions. Consumers receive free treats while companies benefit from accurate market research and increased brand engagement.
As part of the Carthagos team, I was responsible for designing and developing the website landing page. I used WordPress and Elementor to create a clean, responsive layout, integrated Swiper.js for interactive sliders, and applied best practices in HTML, CSS, and JavaScript to ensure cross-device compatibility and smooth user experiences.', '#16D8B3', '#ffffff', 'The landing page successfully showcased Mimoo’s unique value proposition and provided a compelling entry point for both consumers and brands. My work contributed to improved conversion rates, SEO visibility, and mobile responsiveness, which supported the platform’s marketing and user acquisition goals.', 'https://www.mimoogratis.com.br/', 'https://www.carthagos.com/projects/Mimoo', 'portfolio/mimoo/logo.svg', 'portfolio/mimoo/cover2.png', 'live', ARRAY['HTML/CSS', 'JavaScript', 'jQuery', 'WordPress', 'Elementor', 'Swiper.js', 'Responsive Design', 'SEO Optimization']::TEXT[], 3);
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/mimoo/mimoo1.png', 'Main', 'Luminous', 'main', 0, (SELECT "id" FROM "portfolios" WHERE "slug" = 'mimoo'));
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/mimoo/mimoo2.png', 'Why mimoo', 'mimoo', 'secondary', 1, (SELECT "id" FROM "portfolios" WHERE "slug" = 'mimoo'));
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/mimoo/mimoo3.png', 'How It Works', 'gathr', 'alternative', 2, (SELECT "id" FROM "portfolios" WHERE "slug" = 'mimoo'));
INSERT INTO "portfolios" ("slug", "featured", "title", "companyBuiltWith", "desc", "projectColor", "projectText", "outcome", "link", "moreInfoLink", "projectLogo", "image", "status", "skills", "order") VALUES ('nexera-robotics', false, 'Nexara Robotics', 'Carthagos', 'Nexera developed Neuragrasp, a robotics solution for advanced manipulation and grasping technology that adapts to any product, material, or surface with precision and flexibility. The landing page was designed to effectively communicate the innovation and reliability of this technology to potential partners and clients.
I was responsible for developing the website landing page, using WordPress and Elementor to create a clean, responsive, and professional design. I also integrated Swiper.js for interactive content displays and applied HTML, CSS, and JavaScript best practices to ensure smooth navigation, performance optimization, and compatibility across devices.', '#222222', '#E5E5E5', 'The landing page provided Nexera with a modern and user-friendly digital presence to showcase Neuragrasp’s unique technology. It enhanced brand credibility, supported marketing campaigns, and helped attract industry interest by presenting the product’s key features in a clear and engaging way.', 'https://nexera-robotics.com/', 'https://www.carthagos.com/projects/Nexera%20Robotics', 'portfolio/nexera/logo.svg', 'portfolio/nexera/cover2.png', 'live', ARRAY['HTML/CSS', 'JavaScript', 'jQuery', 'WordPress', 'Elementor', 'Swiper.js', 'Responsive Design', 'SEO Optimization']::TEXT[], 4);
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/nexera/nexera1.png', 'Main', 'Luminous', 'main', 0, (SELECT "id" FROM "portfolios" WHERE "slug" = 'nexera-robotics'));
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/nexera/nexera2.png', 'Why nexera', 'nexera', 'secondary', 1, (SELECT "id" FROM "portfolios" WHERE "slug" = 'nexera-robotics'));
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/nexera/nexera3.png', 'How It Works', 'gathr', 'alternative', 2, (SELECT "id" FROM "portfolios" WHERE "slug" = 'nexera-robotics'));
INSERT INTO "portfolios" ("slug", "featured", "title", "companyBuiltWith", "desc", "projectColor", "projectText", "outcome", "link", "moreInfoLink", "projectLogo", "image", "status", "skills", "order") VALUES ('scoutx', false, 'ScoutX', 'Carthagos', 'ScoutX is a modern sports scouting platform that combines AI, social networking, and the gig economy to connect athletes with certified scouts. Through the app, scouts and athletes schedule meetings, exchange feedback, and track performance, making the sports market more accessible and transparent for emerging talent.
As part of the Carthagos team, I designed and developed the landing page for ScoutX. Using WordPress and Elementor, I created a responsive and visually engaging interface to highlight the platform’s unique value. I also implemented Swiper.js for interactive content sections and optimized the site with HTML, CSS, and JavaScript to ensure fast loading times and a smooth user experience across devices.', '#FF695E', '#121016', 'The landing page served as a professional digital entry point for ScoutX, boosting brand visibility and credibility. It effectively communicated the platform’s innovative approach to sports scouting, supported marketing campaigns, and helped attract athletes, scouts, and early adopters.', 'https://scoutxsports.com/', 'https://www.carthagos.com/projects/ScoutX', 'portfolio/scoutx/logo2.svg', 'portfolio/scoutx/cover2.png', 'live', ARRAY['HTML/CSS', 'JavaScript', 'jQuery', 'WordPress', 'Elementor', 'Swiper.js', 'Responsive Design', 'SEO Optimization']::TEXT[], 5);
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/scoutx/scoutx1.png', 'Main', 'Luminous', 'main', 0, (SELECT "id" FROM "portfolios" WHERE "slug" = 'scoutx'));
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/scoutx/scoutx2.png', 'Why scoutx', 'scoutx', 'secondary', 1, (SELECT "id" FROM "portfolios" WHERE "slug" = 'scoutx'));
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/scoutx/scoutx3.png', 'How It Works', 'gathr', 'alternative', 2, (SELECT "id" FROM "portfolios" WHERE "slug" = 'scoutx'));
INSERT INTO "portfolios" ("slug", "featured", "title", "companyBuiltWith", "desc", "projectColor", "projectText", "outcome", "link", "moreInfoLink", "projectLogo", "image", "status", "skills", "order") VALUES ('hassan-store', false, 'Hassan Store', 'HSNA', 'E-Commerce Shopping Web App, where user can buy new or refurbished mobile phones in Pakistan', NULL, NULL, 'I created the landing page of the website.', 'https://www.hassanstore.com/', NULL, NULL, 'portfolio/hassan-store/HassanStore.JPG', 'live', ARRAY['HTML/CSS', 'Javascript', 'Wordpress', 'WooCommerce', 'Ecommerce']::TEXT[], 6);
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/hassan-store/HassanStore.JPG', 'Home Page', 'hassanstore', NULL, 0, (SELECT "id" FROM "portfolios" WHERE "slug" = 'hassan-store'));
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/hassan-store/PhoneCategory.JPG', 'Phone Category', 'hassanstore', NULL, 1, (SELECT "id" FROM "portfolios" WHERE "slug" = 'hassan-store'));
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/hassan-store/PhonePage.JPG', 'Phone Page', 'hassanstore', NULL, 2, (SELECT "id" FROM "portfolios" WHERE "slug" = 'hassan-store'));
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/hassan-store/Cart.JPG', 'Cart', 'hassanstore', NULL, 3, (SELECT "id" FROM "portfolios" WHERE "slug" = 'hassan-store'));
INSERT INTO "portfolios" ("slug", "featured", "title", "companyBuiltWith", "desc", "projectColor", "projectText", "outcome", "link", "moreInfoLink", "projectLogo", "image", "status", "skills", "order") VALUES ('hsna-limited', false, 'HSNA Limited', 'HSNA', 'Company Website of HSNATech', NULL, NULL, 'I created all the webiste dynamically, with admin dashboard. Where admin was able to update the content and portfolio of the website.', 'https://www.hsnatech.com/', NULL, NULL, 'portfolio/hsna-tech/HSNA.JPG', 'live', ARRAY['HTML/CSS', 'Javascript', 'Bootstrap', 'JQuery', 'Ajax', 'PHP', 'MySQL']::TEXT[], 7);
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/hsna-tech/HSNA.JPG', 'Home Page', 'HSNA', NULL, 0, (SELECT "id" FROM "portfolios" WHERE "slug" = 'hsna-limited'));
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/hsna-tech/HSNA1.JPG', 'Services', 'HSNA', NULL, 1, (SELECT "id" FROM "portfolios" WHERE "slug" = 'hsna-limited'));
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/hsna-tech/HSNA2.JPG', 'Portfolio', 'HSNA', NULL, 2, (SELECT "id" FROM "portfolios" WHERE "slug" = 'hsna-limited'));
INSERT INTO "portfolios" ("slug", "featured", "title", "companyBuiltWith", "desc", "projectColor", "projectText", "outcome", "link", "moreInfoLink", "projectLogo", "image", "status", "skills", "order") VALUES ('tripifyy', false, 'Tripifyy', 'Personal Project', 'It is a platform for tourist and trip organiser. where organiser can select services like hotel, transport, restaurant etc and create a trip and touris can join trip. They can also interact via post and comments if tourist have any queries. tourist will be able to rate after the trip is complete.', NULL, NULL, NULL, NULL, NULL, NULL, 'portfolio/tripifyy/Home.JPG', 'underdevelopment', ARRAY['HTML/CSS', 'Javascript', 'Bootstrap', 'ReactJS', 'Redux', 'Web Sockets', 'Express', 'Node.js', 'MongoDB']::TEXT[], 8);
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/tripifyy/Home.JPG', 'Home Page', 'Tripifyy', NULL, 0, (SELECT "id" FROM "portfolios" WHERE "slug" = 'tripifyy'));
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/tripifyy/4.JPG', 'User Home', 'Tripifyy', NULL, 1, (SELECT "id" FROM "portfolios" WHERE "slug" = 'tripifyy'));
INSERT INTO "carousel_items" ("img", "desc", "title", "gridArea", "order", "portfolioId") VALUES ('portfolio/tripifyy/Capture.JPG', 'Organizer Home', 'Tripifyy', NULL, 2, (SELECT "id" FROM "portfolios" WHERE "slug" = 'tripifyy'));

-- Intro 
INSERT INTO "intro" ("firstName", "lastName", "summary", "img", "resume") VALUES ('Najam', 'Uddin', 'Frontend Developer with 6+ years of experience building high-performance, user-focused web applications using React, TypeScript, Tailwind CSS, Next.js and modern frontend tools.', 'front.png', 'Najam_Uddin_Resume.pdf');

-- Services
INSERT INTO "services" ("iconLight", "iconDark", "title", "details", "order") VALUES ('/assets/icons/globe-light.svg', '/assets/icons/globe-dark.svg', 'Modern Frontend Development', 'Turning Figma designs into responsive, pixel-perfect interfaces that deliver smooth user experiences across devices.', 0);
INSERT INTO "services" ("iconLight", "iconDark", "title", "details", "order") VALUES ('/assets/icons/stack-light.svg', '/assets/icons/stack-dark.svg', 'API Integration & State Management', 'Connecting GraphQL/REST APIs with efficient state handling to create seamless, data-driven applications.', 1);
INSERT INTO "services" ("iconLight", "iconDark", "title", "details", "order") VALUES ('/assets/icons/crown-light.svg', '/assets/icons/crown-dark.svg', 'UI/UX Implementation', 'Turning Figma designs into responsive, pixel-perfect interfaces that deliver smooth user experiences across devices.', 2);

-- Education
INSERT INTO "education" ("city", "duration", "academy", "degree", "order") VALUES ('Islamabad, Pakistan', 'Jan 2016 to Jan 2020', 'COMSATS UNIVERSITY OF ISLAMABAD', 'BS Software Engineering', 0);
INSERT INTO "education" ("city", "duration", "academy", "degree", "order") VALUES ('Hyderabad, Pakistan', '2013 to 2015', 'GOVT DEGREE COLLAGE QASIAMABAD', 'Intermediate', 1);
INSERT INTO "education" ("city", "duration", "academy", "degree", "order") VALUES ('Hyderabad, Pakistan', '2011 to 2013', 'AGHA TAJ MUHAMMAD HIGH SCHOOL', 'Matriculation', 2);

-- Work experience
INSERT INTO "work_experience" ("duration", "designation", "company", "location", "icon", "companyDescription", "whatIdid", "skillsUsed", "achievement", "companySite", "order") VALUES ('Jan 2023 - Present', 'Frontend Developer', 'Icecode Software', 'Dubai, UAE', NULL, 'Icecode is a software company that specializes in building all things Software from Apps, ERP''s, CRM''s, to little microservices. As a Frontend Developer, I evaluate project requirements and leverage diverse technical skill sets to develop web applications, designs, and dashboards.', '[{"title":"Frontend Architecture","desc":"Built and optimized scalable dashboards using React 18 and Next.js with modular components and maintainable architecture."},{"title":"API Integration Framework","desc":"Designed and implemented an SDK with GraphQL-Codegen and Apollo Client to standardize API integration."},{"title":"Team Leadership & Code Quality","desc":"Conducted PR reviews, mentored developers, and introduced best practices for React state management and architecture."},{"title":"Testing & Quality Assurance","desc":"Implemented testing standards with Jest and React Testing Library, including snapshot testing for UI reliability."},{"title":"CMS Development","desc":"Developed a React-based CMS with real-time preview to simplify content publishing workflows."}]'::jsonb, ARRAY['React', 'TypeScript', 'Next.js', 'Redux', 'React Context API', 'GraphQL', 'Apollo Client', 'React Query', 'Tailwind CSS', 'JavaScript', 'jQuery', 'MySQL', 'Jest', 'RTL', 'Docker', 'Azure DevOps', 'CI/CD Pipelines', 'Wordpress']::TEXT[], NULL, 'http://carthagos.com', 0);
INSERT INTO "work_experience" ("duration", "designation", "company", "location", "icon", "companyDescription", "whatIdid", "skillsUsed", "achievement", "companySite", "order") VALUES ('June 2020 - Mar 2022', 'Fullstack Developer', 'Carthagos', 'Remote', NULL, 'Carthagos is a global product studio focused on helping start-ups create brands and technologies. The Full Stack Developer evaluates project requirements and maximizes diverse technical skills to develop web applications, designs, and dashboards.', '[{"title":"Data Visualization & Dashboards","desc":"Delivered analytics dashboards with Next.js SSR, React hooks, and reusable UI components."},{"title":"API & Real-Time Integration","desc":"Built GraphQL and REST integrations and added WebSocket support for real-time data updates."},{"title":"Performance Optimization","desc":"Applied React performance optimization techniques, including lazy loading, code-splitting, and caching."},{"title":"UI Development & Accessibility","desc":"Converted Figma designs into responsive React UIs with accessibility and cross-browser support."},{"title":"Mentorship & Best Practices","desc":"Mentored junior developers in React state management and testing practices."}]'::jsonb, ARRAY['React', 'TypeScript', 'Next.js', 'Redux', 'React Context API', 'Tailwind CSS', 'jQuery', 'REST APIs', 'Express.js', 'Node.js', 'MongoDB', 'MySQL', 'Wordpress']::TEXT[], NULL, 'http://carthagos.com', 1);
INSERT INTO "work_experience" ("duration", "designation", "company", "location", "icon", "companyDescription", "whatIdid", "skillsUsed", "achievement", "companySite", "order") VALUES ('Jun 2017 - Present', 'Freelancer', 'Upwork', NULL, NULL, 'Upwork is platfrom for Freelancers', '[{"title":"Service Delivery","desc":"Exhibit strong project management skills and knowledge of technical processes in completing a wide array of projects & milestones, including fixing bugs, mentoring developers, and developing websites and software."},{"title":"Client Relations","desc":"Nurture collaborative relations with clients while maintaining consistent contact to gather and define requirements, develop specifications for project plans, and provide visibility and updates on project progress."},{"title":"Project Management","desc":"Proficiently manage projects, from proposal to completion, leveraging out-of-the-box thinking in solving complex problems and innovating strategic initiatives to achieve client expectations."}]'::jsonb, ARRAY['HTML/CSS/JS', 'ReactJS', 'Wordpress', 'React Native', 'PHP', 'Express']::TEXT[], 'Maintained a +90% job success rate and acquired a top-rated developer badge by consistently delivering quality project output.', '', 2);
INSERT INTO "work_experience" ("duration", "designation", "company", "location", "icon", "companyDescription", "whatIdid", "skillsUsed", "achievement", "companySite", "order") VALUES ('Feb 2018 - Nov 2019', 'Fullstack Developer', 'HSNA Technologies', 'Karachi, Pakistan', NULL, 'HSNA is an IT company that works as a freelance organization, on various projects in view to client''s requirements.', '[{"title":"Web, Applications, and Systems Development","desc":"Maximized knowledge of basic web technologies, including HTML, CSS, Javascript, Bootstrap, jQuery, AJAX, PHP, MySQL, PHPmyAdmin, and WordPress, in developing systems based on client requirements."},{"title":"Team Collaboration","desc":"Communicated with cross-functional teams to identify issues & implement long-term technical solutions."},{"title":"Technical Management","desc":"Applied diverse skillset, impeccable analytical nature, and a capacity to identify, evaluate, and understand the project’s needs and provide an immediate response to technical challenges."}]'::jsonb, ARRAY['HTML/CSS/JS', 'Bootstrap', 'Wordpress', 'PHP', 'MySQL']::TEXT[], 'Demonstrated technical leadership and methodical advice in establishing optimized processes to efficiently direct and implement CRUD, CRM, and CMS applications.', 'https://www.hsnatech.com', 3);

-- Skills
INSERT INTO "skills" ("title", "level", "progress", "order") VALUES ('React', 'Expert', NULL, 0);
INSERT INTO "skills" ("title", "level", "progress", "order") VALUES ('Redux', 'Expert', 85, 1);
INSERT INTO "skills" ("title", "level", "progress", "order") VALUES ('ExressJS', 'Intermediate', NULL, 2);
INSERT INTO "skills" ("title", "level", "progress", "order") VALUES ('NodeJS', 'Intermediate', NULL, 3);
INSERT INTO "skills" ("title", "level", "progress", "order") VALUES ('NextJs', 'Expert', NULL, 4);
INSERT INTO "skills" ("title", "level", "progress", "order") VALUES ('React Native', 'Expert', NULL, 5);
INSERT INTO "skills" ("title", "level", "progress", "order") VALUES ('HTML/CSS', 'Expert', NULL, 6);
INSERT INTO "skills" ("title", "level", "progress", "order") VALUES ('Javascript', 'Expert', NULL, 7);
INSERT INTO "skills" ("title", "level", "progress", "order") VALUES ('Typescript', 'Expert', NULL, 8);
INSERT INTO "skills" ("title", "level", "progress", "order") VALUES ('jQuery', 'Expert', NULL, 9);
INSERT INTO "skills" ("title", "level", "progress", "order") VALUES ('MySQL', 'Expert', NULL, 10);
INSERT INTO "skills" ("title", "level", "progress", "order") VALUES ('MongoDB', 'Expert', NULL, 11);
INSERT INTO "skills" ("title", "level", "progress", "order") VALUES ('C#', 'Intermediate', NULL, 12);
INSERT INTO "skills" ("title", "level", "progress", "order") VALUES ('Blazor', 'Intermediate', NULL, 13);
INSERT INTO "skills" ("title", "level", "progress", "order") VALUES ('Wordpress', 'Expert', NULL, 14);
INSERT INTO "skills" ("title", "level", "progress", "order") VALUES ('PHP', 'Intermediate', NULL, 15);
INSERT INTO "skills" ("title", "level", "progress", "order") VALUES ('Plugin Customization', 'Intermediate', NULL, 16);

-- Testimonials
INSERT INTO "testimonials" ("profile", "name", "designation", "description", "order") VALUES ('/assets/icons/user-solid.svg', 'Amelia Miller', 'Designer', 'We were very pleased to hear how you resolved our website''s user interface issues and challenges.', 0);
INSERT INTO "testimonials" ("profile", "name", "designation", "description", "order") VALUES ('/assets/icons/user-tie-solid.svg', 'James Delaney', 'Developer', 'I’m glad I decided to work with you. The project was delivered on time with all the requirements.', 1);

-- Contact info
INSERT INTO "contact_info" ("text", "iconLight", "iconDark", "link", "order") VALUES (ARRAY['Islamabad, Pakistan']::TEXT[], '/assets/icons/pin-light.svg', '/assets/icons/pin-dark.svg', 'https://maps.app.goo.gl/vwWZJ9z5Sq8B2VJm7', 0);
INSERT INTO "contact_info" ("text", "iconLight", "iconDark", "link", "order") VALUES (ARRAY['+92 335 5943502']::TEXT[], '/assets/icons/phone-call-purple.svg', '/assets/icons/phone-call-dark.svg', 'tel:+923355943502', 1);
INSERT INTO "contact_info" ("text", "iconLight", "iconDark", "link", "order") VALUES (ARRAY['najam.u1011@gmail.com']::TEXT[], '/assets/icons/mail-light.svg', '/assets/icons/mail-dark.svg', 'mailto:najam.u1011@gmail.com', 2);

